### ISSUE TITLE
Not sure how to run ex2

### ISSUE THREAD

**Issue by jiashenC** [sstsimulator/sst-tutorials#1]
The trouble I am having now is how to run **SST** along with **Python** config file. I try the following command.
```bash
sst ex2.py -c miranda.cfg
```
However, I will get error below.
```
sst: invalid option -- 'c'
```

How can I pass the command line argument to `ex2.py` **Python** file instead of `sst` command?

**Comment by jjwilke** [comment]
Hi Jiashen,

I think what you want is --model-options.

if you run:
sst ex2.py --model-options="here are my args"

using the file ex2.py:
import sys
print sys.args

Output: "here are my args"

Let me know if you're intending to do something else.

-Jeremy

**Comment by jiashenC** [comment]
Thanks for the quick reply. That solves my issue. Thanks!
